# --- Paleta de Colores Blanco y Negro ---
$foreground = rgb(e0e0e0)      # Blanco suave (no cansa la vista)
$background = rgba(101010ee)   # Negro profundo con un toque de transparencia
$cursor = rgb(ffffff)

# Variaciones de Grises para la UI
$color0 = rgb(1a1a1a)          # Negro puro
$color8 = rgb(333333)          # Gris oscuro (Inactivos)
$color7 = rgb(b0b0b0)          # Gris claro
$color15 = rgb(ffffff)         # Blanco puro (Resaltados)

# Acentos (Escala de grises)
$color1 = rgb(444444)
$color2 = rgb(666666)
$color4 = rgb(888888)
