windowrule {
  name = stats-workspace
  match:class = stat-window
  workspace = special:magic
}

windowrule {
  name = steam
  match:class = steam 
  workspace = 4
}

windowrule {
  name = discord
  match:class = discord-canary 
  workspace = special:F3
}
windowrule {
  name = spotify
  match:class = Spotify
  workspace = special:F2
}
