# Aplica blur a la capa que queda detrás de las ventanas flotantes/especiales
#layerrule = blur, speciallock
#layerrule = blur, floating

# Youtube
# workspace = special:scratch, on-created-empty:[float] alacritty
windowrule {
  name = stats-workspace
  match:class = stat-window
  workspace = special:magic
}
