workspace = special:magic, gapsin:10, gapsout:60
workspace = special:F1, gapsin:10, gapsout:40 
workspace = special:F2, gapsin:10, gapsout:40 
workspace = special:F3, gapsin:10, gapsout:40 
workspace = special:F4, gapsin:10, gapsout:40 
workspace = special:F5, gapsin:10, gapsout:40 
workspace = special:F6, gapsin:10, gapsout:40 
