hl.on("hyprland.start", function()
  hl.exec_cmd("hypridle")
  hl.exec_cmd("waybar")
	-- hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("awww-daemon && awww img ~/Pictures/Wallpapers/pinguino.png")
	-- hl.exec_cmd("hyprsunset")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("rfkill unblock bluetooth")
end)
