[[mgr.prepend_keymap]]
on  = "<C-n>"
run = "shell -- dragon-drop --and-exit %h"

[[mgr.prepend_keymap]]
desc = "Start bunny.yazi"
on = "'"
run = "plugin bunny"

[[mgr.prepend_keymap]]
desc = "Start bunny.yazi fuzzy search"
on = ";"
run = "plugin bunny fuzzy"


[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin wl-clipboard"]
