set -g default-shell /bin/zsh

# Options
set -g mouse on
set -g set-clipboard on
set -g status-interval 3
set -g detach-on-destroy off

# Yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber windows when one is closed

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin '27medkamal/tmux-session-wizard'

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_with_mouse off

set -g @plugin 'christoomey/vim-tmux-navigator'

# STATUS BAR
set -g status-position top

set -g status-style "bg=black,fg=white"

set -g status-left "#[bg=white,fg=black,bold] #S #[bg=black,fg=white]"

setw -g window-status-format " #[fg=white]#I:#W "

setw -g window-status-current-format "#[bg=white,fg=black,bold] #I:#W #[bg=black,fg=white]"

set -g status-right ""

# BORDERS
set -g pane-border-style "fg=#444444"
set -g pane-active-border-style "fg=#444444"
set -g message-style "bg=white,fg=black,bold"

# KEYS
unbind r
bind r source-file ~/.tmux.conf

unbind C-b
set -g prefix C-s

unbind %
unbind h
bind h split-window -h -c "#{pane_current_path}"

unbind \"
unbind v
bind v split-window -v -c "#{pane_current_path}"

unbind t
bind t new-window -c "#{pane_current_path}"

bind x kill-pane
bind & kill-window

bind -r m resize-pane -Z

bind -n C-S-h select-window -p
bind -n C-S-l select-window -n

bind -n C-S-j switch-client -p
bind -n C-S-k switch-client -n

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -sel clip"

bind S command-prompt -p "New Session:" "new-session -A -s '%%'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
